
POST http://localhost:3001/admin/courtentry
content-type: application/json

{
    "org": "court",
    "courtId": "court2@gmail.com",
    "location": "Dhaka",
    "judgeSign": "mr kashem",
    "password": "123456" 
}

###
POST http://localhost:3001/admin/courtentry
content-type: application/json

{
    "courtId": "court@gmail.com",
    "location": "Narayanganj",
    "judgeSign": "mr boltu",
    "password": "123456"
}

###
POST http://localhost:3001/admin/jailentry
content-type: application/json

{
    "org": "jail",
    "jailId": "jail@gmail.com",
    "location": "Narayanganj",
    "dSign": "njail",
    "password": "123456"
}
###

POST http://localhost:3001/admin/jailentry
content-type: application/json

{
    "org": "jail",
    "jailId": "jail2@gmail.com",
    "location": "Sylhet",
    "dSign": "sjail",
    "password": "123456"
}

###
POST http://localhost:3001/login/court
content-type: application/json

{
    "email": "court@gmail.com",
    "password": "123456" 
}
###
POST http://localhost:3001/login/jail
content-type: application/json

{
    "jailId": "12345678",
    "password": "123456" 
}

###

POST http://localhost:3001/court/criminalentry
content-type: application/json

{
    "name": "Omar Sultan",
    "date": "1-1-1998",
    "email": "court@gmail.com",
    "nid": "122233333",
    "jailName": "kashimpur",
    "jailID": "420420",
    "punishmentStartDate": "null",
    "punishmentEndDate": "null",
    "courtID": "court@gmail.com",
    "gender": "male",
    "crime": "do nothing"
}

###

POST http://localhost:3001/court/criminalentry
content-type: application/json

{
    "name": "Arif Shahriar",
    "dob": "1-1-1998",
    "gender": "Male",
    "nationality": "Bangladeshi",
    "crimeDesc": "used chatgpt",
    "nid": "420421",
    "pStartTime": "null",
    "pEndTime": "null",
    "courtId": "court@gmail.com",
    "jailId": "jail@gmail.com"
}

###

POST http://localhost:3001/login/jail
content-type: application/json

{
    "jailId": "12345678",
    "password": "123456" 
}

###
GET http://localhost:3001/court/criminals

###
GET http://localhost:3001/criminal/list

###
GET http://localhost:3001/jail/criminals
content-type: application/json

###
GET http://localhost:3001/logout
content-type: application/json


###
// getting error
POST http://localhost:3001/court/updatecriminal  
content-type: application/json

{
    "name": "Md Arif Shahriar",
    "dob": "1-1-1998",
    "gender": "Male",
    "nationality": "Bangladeshi",
    "crimeDesc": "used chatgpt",
    "nid": "420420",
    "pStartTime": "null",
    "pEndTime": "null",
    "courtId": "12345678",
    "jailId": "23456789"
}

### 
DELETE http://localhost:3001/court/deletecriminal
content-type: application/json

{
    "nid": "420420"
}

###

GET http://localhost:3001/criminal/:"122233333"
Content-Type: application/json



### 
POST http://localhost:3001/count
Content-Type: application/json

{
    "court": 0,
    "jail": 0,
    "passport": 0,
    "police": 0,
    "criminal": 0
}


###
GET http://localhost:3001/count

###
GET http://localhost:3001/transaction

###
GET http://localhost:3001/organizations

// court and jail attribute have to be same to fetch data